version: '2'
services:
  app:
    #https://github.com/rmsaitam/laravel8-jetstream-docker
    build:
      context: ./jetstream
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=agenda.jet
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 8000:80 #apache
    volumes:
      - ./www/:/var/www/html/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
    depends_on: 
      - mariadb
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password